name: LazyLumberjack
version: '${version}'
main: dev.boostio.lazylumberjack.LazyLumberjack
api-version: '1.13'
folia-supported: true
depend:
  - packetevents

permissions:
  LazyLumberjack.Use:
    description: Allows the player to log lazily.
    default: op
